export const Icons = {
  logo: require('../assets/images/logo.png'),
  home: require('../assets/images/home.png'),
  home_active: require('../assets/images/home-active.png'),
  dine_in: require('../assets/images/dine-in.png'),
  location: require('../assets/images/location.png'),
  user: require('../assets/images/user.png'),
  takeaway: require('../assets/images/takeaway.png'),
};

export const Fonts = {
  Poppins_Black: 'Poppins-Black',
  Poppins_BlackItalic: 'Poppins-BlackItalic',
  Poppins_Bold: 'Poppins-Bold',
  Poppins_BoldItalic: 'Poppins-BoldItalic',
  Poppins_ExtraBold: 'Poppins-ExtraBold',
  Poppins_ExtraBoldItalic: 'Poppins-ExtraBoldItalic',
  Poppins_ExtraLight: 'Poppins-ExtraLight',
  Poppins_ExtraLightItalic: 'Poppins-ExtraLightItalic',
  Poppins_Italic: 'Poppins-Italic',
  Poppins_Light: 'Poppins-Light',
  Poppins_LightItalic: 'Poppins-LightItalic',
  Poppins_Medium: 'Poppins-Medium',
  Poppins_MediumItalic: 'Poppins-MediumItalic',
  Poppins_Regular: 'Poppins-Regular',
  Poppins_SemiBold: 'Poppins-SemiBold',
  Poppins_SemiBoldItalic: 'Poppins-SemiBoldItalic',
  Poppins_Thin: 'Poppins-Thin',
  Poppins_ThinItalic: 'Poppins-ThinItalic',
  OpenSans_LightItalic: 'OpenSans-LightItalic',
  OpenSans_Medium: 'OpenSans-Medium',
  OpenSans_SemiBold: 'OpenSans-SemiBold',
  OpenSans_Regular: 'OpenSans-Regular',
  OpenSans_MediumItalic: 'OpenSans-MediumItalic',
  OpenSans_Light: 'OpenSans-Light',
  OpenSans_Bold: 'OpenSans-Bold',
  OpenSans_Condensed_ExtraBold: 'OpenSans_Condensed-ExtraBold',
};
